export const meta = {
  name: 'ev27-smoketest',
  description: 'EV27 小樣本 v6:純質化消息面歸因 × 2 批(暴漲 8 + 偽形 8)',
  phases: [{ title: 'Attribution' }],
}
const S_SCHEMA = {"type": "object", "properties": {"findings": {"type": "array", "items": {"type": "object", "properties": {"code": {"type": "string"}, "driver_narrative": {"type": "string", "maxLength": 500}, "pre_t0_news": {"type": "array", "items": {"type": "object", "properties": {"date": {"type": "string"}, "source": {"type": "string"}, "content": {"type": "string", "maxLength": 200}, "pricing_state": {"type": "string", "maxLength": 30}}, "required": ["date", "source", "content"], "additionalProperties": false}}, "post_t0_news": {"type": "array", "items": {"type": "object", "properties": {"date": {"type": "string"}, "source": {"type": "string"}, "content": {"type": "string", "maxLength": 200}, "pricing_state": {"type": "string", "maxLength": 30}}, "required": ["date", "source", "content"], "additionalProperties": false}}, "catalyst_verdict": {"type": "string", "maxLength": 60}}, "required": ["code", "driver_narrative", "pre_t0_news", "post_t0_news", "catalyst_verdict"], "additionalProperties": false}}, "patterns": {"type": "string", "maxLength": 3000}, "news_report": {"type": "string", "maxLength": 1800}}, "required": ["findings", "patterns", "news_report"], "additionalProperties": false}
const C_SCHEMA = {"type": "object", "properties": {"findings": {"type": "array", "items": {"type": "object", "properties": {"code": {"type": "string"}, "why_failed_narrative": {"type": "string", "maxLength": 500}, "pre_t0_news": {"type": "array", "items": {"type": "object", "properties": {"date": {"type": "string"}, "source": {"type": "string"}, "content": {"type": "string", "maxLength": 200}, "pricing_state": {"type": "string", "maxLength": 30}}, "required": ["date", "source", "content"], "additionalProperties": false}}, "news_diagnosis": {"type": "string", "maxLength": 400}}, "required": ["code", "why_failed_narrative", "pre_t0_news", "news_diagnosis"], "additionalProperties": false}}, "patterns": {"type": "string", "maxLength": 3000}, "news_report": {"type": "string", "maxLength": 1800}}, "required": ["findings", "patterns", "news_report"], "additionalProperties": false}
const P_SURGE = "你是台股資深研究總監。以下 8 檔股票在 2022-2025 年間,各自於 60 個交易日內上漲超過 80%:\n\n- 2364 倫飛(電腦及週邊設備業),t0 = 2022-07-01,60 日漲幅 +328%\n- 3661 世芯-KY(半導體業),t0 = 2025-04-22,60 日漲幅 +88%\n- 4768 晶呈科技(化學工業),t0 = 2022-07-08,60 日漲幅 +97%\n- 8933 愛地雅(其他),t0 = 2022-07-01,60 日漲幅 +126%\n- 1519 華城(電機機械),t0 = 2023-11-30,60 日漲幅 +100%\n- 3583 辛耘(半導體業),t0 = 2024-01-02,60 日漲幅 +81%\n- 4402 郡都開發(紡織纖維),t0 = 2024-01-05,60 日漲幅 +83%\n- 2348 海悅(其他),t0 = 2024-01-08,60 日漲幅 +84%\n\n你的任務是**消息面歸因**:重建每一檔在 t0 前後的消息與題材全貌,回答「它為什麼暴漲——當時的世界發生了什麼」。(t0 的操作型定義:該檔 60 個交易日內上漲超過 80% 的那段漲勢的**起點日**。)量化面(價量、營收數字、籌碼)的判別由另一套量化系統負責,不是你的任務;你是整個研究中唯一負責「質化真相」的人,你找到的消息證據無可替代。\n\n用 WebSearch / WebFetch 搜尋。搜尋的完成標準不是輪數,而是:**你能夠有把握地回答「這檔股票 t0 之前的消息面全貌是什麼、存在哪些可事前識別的催化」——或有把握地確認「查無 t0 前消息」為止**。\n\n搜尋範圍**包含但絕不限於**:法說會與財測、接單/訂單/客戶、擴產/新廠/資本支出、認證/打入供應鏈、產業報價與供需、政策與法規、併購/分拆/私募、新產品/新技術、經營權與人事、題材點火事件(國際大廠發表、地緣事件、政策計畫)、市場傳聞與社群討論——**什麼類型的消息有價值,正是本研究要回答的問題,任何你認為可能相關的線索都值得追**。\n\n消息來源地圖(僅為地圖、降低探路成本,**不受此清單限制**):\n- **一手權威源**:公開資訊觀測站 MOPS(公告+法說行事曆與簡報 PDF,自帶精確日期)、公司官網 IR/新聞室\n- **法說會內容**:AlphaMemo(alphamemo.ai/free-transcripts,台股法說逐字稿+摘要;登入牆 → 用使用者 Chrome)、富果法說會備忘錄(blog.fugle.tw/topic/earnings-call-memo,中小型股覆蓋佳)、Seeking Alpha / Motley Fool(ADR 英文 transcript)、YouTube 法說回放。讀法說時挖 **supplier read-through**(別家公司法說裡透露的供應鏈訊號),不只看發表公司本身\n- **產業媒體**:DigiTimes(供應鏈第一手)、工商時報、經濟日報/UDN 產業版、TechNews、鉅亨網 cnyes、MoneyDJ、中央社、財訊、今周刊、富果研究部(blog.fugle.tw/topic/industry-analysis 供應鏈深度報告、topic/stock-analysis 中小型深研)\n- **報價/供需數據**:TrendForce/DRAMeXchange(記憶體)、SMM 上海有色(材料)、各產業公協會\n- **OSINT**:Wayback Machine(**看歷史時點的網頁原貌**——公司當時的官網、合作夥伴頁、產品頁,對回溯研究極有價值)、LinkedIn 職缺(擴產訊號)、PTT Stock 板、X(Twitter)歷史推文\n- **工具備援**:WebFetch 被登入牆/JS/反爬擋下時,改用**使用者的 Chrome 瀏覽器**(claude-in-chrome MCP 工具,先以 ToolSearch 載入 `mcp__claude-in-chrome__*`;使用者已登入各站)。Chrome 是共享資源:僅在 WebFetch 失敗時使用、一次一個分頁、用完關閉。\n\n鐵律:\n1. 每條採用的消息必須記錄**發佈日期與來源**。無法確認日期的資訊不得作為前兆證據(可另註為「日期不明的旁證」)。\n2. **嚴格分開兩類**:(a) t0 之前已可公開得知的消息——可用於事前判斷的前兆;(b) t0 之後才出現的消息——只能用於事後理解驅動,必須標明「事後」。混淆兩者會污染整個研究。\n3. 搜不到就誠實記錄「查無 t0 前消息面」——這本身是重要發現(存在無消息的暴漲)。**禁止腦補不存在的新聞**。\n\n消息資料持久化(必做):每檔研究完成時,把你搜集到的**全部**消息材料用 Write 工具存到 `/Users/zaoldyeck/Documents/scala/quantlib/src/quantlib/evergreen/data/ev27_news/{code}_{t0}.json`——格式為 JSON 陣列,每條:`{\"date\": 發佈日期, \"source\": 來源, \"url\": 連結, \"title\": 標題, \"excerpt\": 重點摘錄(保留原文關鍵句,≤500 字), \"pit\": \"pre_t0\" 或 \"post_t0\", \"pricing_state\": 定價狀態}`。這是永久資產:未來任何回測與重分析直接讀檔,不再重新搜尋。沒有被你採用為證據、但搜尋中看過且可能有價值的材料也一併存入(標 `\"used\": false`)。\n\n\n對每一檔輸出:\n1. `driver_narrative`:它為什麼暴漲(≤250 字)——當時世界發生了什麼、因果鏈是什麼。\n2. `pre_t0_news`:**t0 前可見的消息清單**(本研究最重要的產出)——每條含:日期、來源、一句話內容、你判斷它當時的「定價狀態」(市場尚未反應/部分反應/人盡皆知)。\n3. `post_t0_news`:t0 後才出現、對理解驅動重要的消息(標明事後)。\n4. `catalyst_verdict`:消息面在這次暴漲中的角色——主催化(消息點火)/醞釀型(消息早已存在、後被重新定價)/查無消息(純資金/籌碼行情)。\n\n最後綜觀本批 8 檔:\n- `patterns`:共同模式(≤1500 字)——什麼樣的消息、在什麼條件下,最終演成暴漲。\n- `news_report`:消息面判別力總評(≤900 字)——本批中什麼類型的消息在 t0 前真的預示了暴漲(類型 × 消息時齡 × 定價狀態 × **消息與 t0 的時間距離**),以及「查無消息」暴漲的占比與特徵。\n\n輸出 JSON(繁體中文)。"
const P_CTRL = "你是台股資深研究總監。以下 8 檔股票是「假訊號對照組」:它們在 t0 前 120 日都曾上漲 25% 以上、表面上像即將起漲的候選,但接下來 60 個交易日最高漲幅不到 20%:\n\n- 8097 常珵(通信網路業),t0 = 2022-07-22,前期漲幅 +116%,後續 60 日最高僅 +13%\n- 2736 富野(觀光餐旅),t0 = 2022-10-07,前期漲幅 +43%,後續 60 日最高僅 +0%\n- 6568 宏觀(半導體業),t0 = 2023-01-12,前期漲幅 +28%,後續 60 日最高僅 +13%\n- 6242 立康(生技醫療業),t0 = 2023-04-26,前期漲幅 +50%,後續 60 日最高僅 +18%\n- 6231 系微(資訊服務業),t0 = 2024-01-02,前期漲幅 +143%,後續 60 日最高僅 +14%\n- 9939 宏全(其他),t0 = 2024-04-10,前期漲幅 +42%,後續 60 日最高僅 +18%\n- 6768 志強-KY(運動休閒),t0 = 2025-03-12,前期漲幅 +51%,後續 60 日最高僅 +-2%\n- 4541 晟田(其他),t0 = 2025-05-05,前期漲幅 +59%,後續 60 日最高僅 +17%\n\n你的任務是**消息面診斷**:重建每一檔在 t0 前後的消息與題材全貌,回答「它看起來像會漲、為什麼最終沒有漲」。(t0 的操作型定義:觀察時點——該檔在此前 120 個交易日已上漲 25% 以上、外觀像即將起漲的候選,但此後 60 個交易日最高漲幅不到 20%。)量化面的判別由另一套量化系統負責,不是你的任務;你是整個研究中唯一負責「質化真相」的人。\n\n用 WebSearch / WebFetch 搜尋。搜尋的完成標準不是輪數,而是:**你能夠有把握地回答「這檔股票 t0 前的消息面全貌、以及它前期上漲的消息基礎是什麼」——或有把握地確認「查無消息」為止**。\n\n搜尋範圍**包含但絕不限於**:法說會與財測、接單/訂單/客戶、擴產/新廠、認證/供應鏈、產業報價、政策法規、併購、新產品、經營權與人事、題材事件、市場傳聞與社群討論——**什麼消息特徵能識別偽形,正是本研究要回答的問題,任何線索都值得追**。\n\n消息來源地圖(僅為地圖、降低探路成本,**不受此清單限制**):\n- **一手權威源**:公開資訊觀測站 MOPS(公告+法說行事曆與簡報 PDF,自帶精確日期)、公司官網 IR/新聞室\n- **法說會內容**:AlphaMemo(alphamemo.ai/free-transcripts,台股法說逐字稿+摘要;登入牆 → 用使用者 Chrome)、富果法說會備忘錄(blog.fugle.tw/topic/earnings-call-memo,中小型股覆蓋佳)、Seeking Alpha / Motley Fool(ADR 英文 transcript)、YouTube 法說回放。讀法說時挖 **supplier read-through**(別家公司法說裡透露的供應鏈訊號),不只看發表公司本身\n- **產業媒體**:DigiTimes(供應鏈第一手)、工商時報、經濟日報/UDN 產業版、TechNews、鉅亨網 cnyes、MoneyDJ、中央社、財訊、今周刊、富果研究部(blog.fugle.tw/topic/industry-analysis 供應鏈深度報告、topic/stock-analysis 中小型深研)\n- **報價/供需數據**:TrendForce/DRAMeXchange(記憶體)、SMM 上海有色(材料)、各產業公協會\n- **OSINT**:Wayback Machine(**看歷史時點的網頁原貌**——公司當時的官網、合作夥伴頁、產品頁,對回溯研究極有價值)、LinkedIn 職缺(擴產訊號)、PTT Stock 板、X(Twitter)歷史推文\n- **工具備援**:WebFetch 被登入牆/JS/反爬擋下時,改用**使用者的 Chrome 瀏覽器**(claude-in-chrome MCP 工具,先以 ToolSearch 載入 `mcp__claude-in-chrome__*`;使用者已登入各站)。Chrome 是共享資源:僅在 WebFetch 失敗時使用、一次一個分頁、用完關閉。\n\n鐵律:\n1. 每條採用的消息必須記錄**發佈日期與來源**;無法確認日期者不得作為事前證據。\n2. **嚴格分開** t0 前可得知 vs t0 後才出現的消息(後者標明「事後」)。\n3. 搜不到就誠實記錄「查無」,**禁止腦補**。\n\n消息資料持久化(必做):每檔研究完成時,把你搜集到的**全部**消息材料用 Write 工具存到 `/Users/zaoldyeck/Documents/scala/quantlib/src/quantlib/evergreen/data/ev27_news/{code}_{t0}.json`——格式為 JSON 陣列,每條:`{\"date\": 發佈日期, \"source\": 來源, \"url\": 連結, \"title\": 標題, \"excerpt\": 重點摘錄(保留原文關鍵句,≤500 字), \"pit\": \"pre_t0\" 或 \"post_t0\", \"pricing_state\": 定價狀態}`。這是永久資產:未來任何回測與重分析直接讀檔,不再重新搜尋。沒有被你採用為證據、但搜尋中看過且可能有價值的材料也一併存入(標 `\"used\": false`)。\n\n\n對每一檔輸出:\n1. `why_failed_narrative`:為什麼它沒有漲(≤250 字)——前期漲勢的本質是什麼、缺了什麼。\n2. `pre_t0_news`:t0 前可見的消息清單——每條含日期、來源、內容、定價狀態判斷(特別注意:**這檔的消息是不是「早已人盡皆知的舊聞」「已充分定價的利多」「無實質的題材蹭貼」**)。\n3. `news_diagnosis`:消息面診斷結論——有消息而不漲的原因(利多出盡/舊聞重炒/蹭題材無卡位/消息與事實矛盾),或無消息時前期漲勢靠什麼、為何續航失敗。\n\n最後綜觀本批 8 檔:\n- `patterns`:共同假訊號模式(≤1500 字)。\n- `news_report`:消息面識別偽形的判別力總評(≤900 字)——什麼樣的消息特徵(類型/時齡/定價狀態/與漲勢的時序關係)在 t0 前就能識別出「這次不會成」。\n\n輸出 JSON(繁體中文)。"
phase('Attribution')
const out = await parallel([
  () => agent(P_SURGE, { label: 'surge-smoke', schema: S_SCHEMA, model: 'opus', effort: 'max' })
    .then(v => v && { ...v, batch: 'surge_smoke' }),
  () => agent(P_CTRL, { label: 'ctrl-smoke', schema: C_SCHEMA, model: 'opus', effort: 'max' })
    .then(v => v && { ...v, batch: 'control_smoke' }),
])
return out.filter(Boolean)
