"""iter_34 - core/satellite portfolio construction for TW stocks.

First-principles conclusion from iter_33:

* A concentrated acceleration sleeve can produce very high CAGR, but the drawdown
  is too large to be a standalone PM-grade portfolio.
* Taiwan equity returns have a persistent structural core: 2330 total-return
  compounding.
* A static capital split between 2330 core and the concentrated PM3 satellite
  keeps the mandate simple, long-only, and under the 10-stock limit.

This file is intentionally a fast portfolio-construction layer. It consumes
daily NAVs generated by:

  * latest_hold_2330_daily.csv
  * iter_33_pm_3pos_concentrated_daily.csv

No full feature panel is rebuilt here. Re-run iter_33 only when the PM3
satellite needs to be regenerated.
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np
import polars as pl


CAPITAL = 1_000_000.0
RF = 0.01
TDPY = 252
RESULTS = Path("research/strat_lab/results")


def metrics(nav: np.ndarray, days: list, capital: float | None = None) -> dict[str, float]:
    nav = np.asarray(nav, dtype=float)
    if len(nav) < 2:
        raise ValueError("need at least two NAV rows")
    base = float(capital if capital is not None else nav[0])
    rets = np.diff(nav) / nav[:-1]
    years = max((days[-1] - days[0]).days / 365.25, 1e-9)
    cagr = (nav[-1] / nav[0]) ** (1 / years) - 1
    vol = float(rets.std(ddof=1) * math.sqrt(TDPY)) if len(rets) > 1 else 0.0
    downside = rets[rets < 0]
    downvol = float(downside.std(ddof=1) * math.sqrt(TDPY)) if len(downside) > 1 else 1e-9
    peak = base
    mdd = 0.0
    for v in nav:
        peak = max(peak, float(v))
        mdd = min(mdd, (float(v) - peak) / peak)
    return {
        "cagr": float(cagr),
        "sortino": float((cagr - RF) / downvol) if downvol > 0 else 0.0,
        "sharpe": float((cagr - RF) / vol) if vol > 0 else 0.0,
        "mdd": float(mdd),
        "final_nav": float(nav[-1]),
    }


def load_nav(path: Path, name: str) -> pl.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"missing required NAV file: {path}")
    return pl.read_csv(path, try_parse_dates=True).select(["date", "nav"]).rename({"nav": name})


def build_panel() -> pl.DataFrame:
    core = load_nav(RESULTS / "latest_hold_2330_daily.csv", "core_2330")
    sat = load_nav(RESULTS / "iter_33_pm_3pos_concentrated_daily.csv", "sat_pm3")
    hybrid = load_nav(RESULTS / "latest_true_3q_7c_best_w60_daily.csv", "hybrid_3q7_w60")
    return core.join(sat, on="date", how="inner").join(hybrid, on="date", how="inner").sort("date")


def sweep_weights(panel: pl.DataFrame, weights: list[float]) -> pl.DataFrame:
    rows = []
    days = panel["date"].to_list()
    core = panel["core_2330"].to_numpy()
    sat = panel["sat_pm3"].to_numpy()
    for w in weights:
        nav = w * core + (1.0 - w) * sat
        core_pct = round(w * 100)
        sat_pct = round((1.0 - w) * 100)
        rows.append({"strategy": f"core_sat_{core_pct}_{sat_pct}", "w_2330": w, **metrics(nav, days)})
    for col in ["core_2330", "sat_pm3", "hybrid_3q7_w60"]:
        rows.append({"strategy": col, "w_2330": None, **metrics(panel[col].to_numpy(), days)})
    return pl.DataFrame(rows).sort(["sortino", "cagr"], descending=[True, True])


def validate_periods(panel: pl.DataFrame) -> pl.DataFrame:
    periods = [
        ("Full", "2005-01-03", "2026-05-08"),
        ("OOS_2013", "2013-01-01", "2026-05-08"),
        ("OOS_2017", "2017-01-01", "2026-05-08"),
        ("COVID_plus", "2020-01-01", "2026-05-08"),
        ("Recent_2022", "2022-01-01", "2026-05-08"),
    ]
    rows = []
    for period, start, end in periods:
        sub = panel.filter((pl.col("date") >= pl.lit(start).str.to_date()) & (pl.col("date") <= pl.lit(end).str.to_date()))
        if sub.height < 3:
            continue
        days = sub["date"].to_list()
        for col in ["core_sat_60_40", "core_sat_70_30", "hybrid_3q7_w60", "core_2330", "sat_pm3"]:
            rows.append({"period": period, "strategy": col, **metrics(sub[col].to_numpy(), days)})
    return pl.DataFrame(rows)


def yearly_returns(panel: pl.DataFrame) -> pl.DataFrame:
    rows = []
    for year in range(2005, 2027):
        sub = panel.filter(pl.col("date").dt.year() == year)
        if sub.height < 2:
            continue
        for col in ["core_sat_60_40", "hybrid_3q7_w60", "core_2330", "sat_pm3"]:
            rows.append({"year": year, "strategy": col, "ret": float(sub[col][-1] / sub[col][0] - 1)})
    return pl.DataFrame(rows)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--core-weight", type=float, default=0.60, help="initial capital weight in 2330 core")
    args = ap.parse_args()
    if not 0 <= args.core_weight <= 1:
        raise ValueError("--core-weight must be in [0, 1]")

    RESULTS.mkdir(parents=True, exist_ok=True)
    panel = build_panel()
    panel = panel.with_columns(
        [
            (0.60 * pl.col("core_2330") + 0.40 * pl.col("sat_pm3")).alias("core_sat_60_40"),
            (0.70 * pl.col("core_2330") + 0.30 * pl.col("sat_pm3")).alias("core_sat_70_30"),
            (args.core_weight * pl.col("core_2330") + (1.0 - args.core_weight) * pl.col("sat_pm3")).alias("nav"),
        ]
    )

    chosen = int(args.core_weight * 100)
    daily_path = RESULTS / f"iter_34_core_satellite_w{chosen}_daily.csv"
    panel.select(["date", "nav", "core_2330", "sat_pm3", "hybrid_3q7_w60"]).write_csv(daily_path)

    weight_sweep = sweep_weights(panel, [i / 10 for i in range(11)])
    sweep_path = RESULTS / "iter_34_core_satellite_weight_sweep.csv"
    weight_sweep.write_csv(sweep_path)

    validation = validate_periods(panel)
    validation_path = RESULTS / "iter_34_core_satellite_validation.csv"
    validation.write_csv(validation_path)

    yearly = yearly_returns(panel)
    yearly_path = RESULTS / "iter_34_core_satellite_yearly.csv"
    yearly.write_csv(yearly_path)

    print("=" * 96)
    print("iter_34 core/satellite weight sweep")
    print("=" * 96)
    print(
        weight_sweep.select(
            [
                "strategy",
                "w_2330",
                pl.col("cagr").mul(100).round(2).alias("cagr_pct"),
                pl.col("sortino").round(3),
                pl.col("sharpe").round(3),
                pl.col("mdd").mul(100).round(2).alias("mdd_pct"),
                pl.col("final_nav").round(0),
            ]
        )
        .head(12)
        .to_pandas()
        .to_string(index=False)
    )
    print(f"\nSaved: {daily_path}")
    print(f"Saved: {sweep_path}")
    print(f"Saved: {validation_path}")
    print(f"Saved: {yearly_path}")


if __name__ == "__main__":
    main()
